# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0873099f78c13effca750bbdbd1bd5c0c99ab9604277d2e9553c3e63648d403d29adc129b049fa9c5d0e6c0d2ad9c2461351526c6652c559ad4712e16b051a83

test:
  secret_key_base: 13dedbe8ffbccf3973ee77dd298c2189857d66016ddf31e0a55dc11e3c1623e2c34ca5bc280dcca8061276b031b565aa5a89547e06e141ebeed1f097875f73cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
